- hosts: all
  become: yes
  become_method: sudo
  roles:
    - common

- hosts: master
  become: yes
  become_method: sudo
  roles:
    - registry
    - k3s/master

- hosts: node
  become: yes
  become_method: sudo
  roles:
    - k3s/node