- name: Add cetic chart repo
  community.kubernetes.helm_repository:
    name: cetic
    repo_url: "https://cetic.github.io/helm-charts"

- name: Ghost helm release stat
  community.kubernetes.helm_info:
    name: ghost
    release_namespace: ghost
  register: ghost_stat


- name: Install ghost helm release
  # shell: helm --namespace=traefik upgrade -i --reset-values --wait --create-namespace traefik traefik/traefik
  community.kubernetes.helm:
    name: ghost
    chart_ref: cetic/microservice
    release_namespace: ghost
    create_namespace: yes
    wait: yes
  when: ghost_stat.status is not defined

- name: Add ghost ingress
  community.kubernetes.k8s:
    state: present
    apply: yes
    definition:
      apiVersion: traefik.containo.us/v1alpha1
      kind: IngressRoute
      metadata:
        name: ghost-ingress
        namespace: ghost
      spec:
        entryPoints:
          - web
        routes:
          - match: Host(`ghost.kube`)
            kind: Rule
            services:
              - name: ghost-microservice-svc-web
                kind: Service
                namespace: ghost
                scheme: http
                port: 8000